<?php

namespace Hestec\ExactOnline;

use SilverStripe\CMS\Model\SiteTree;
use SilverStripe\Forms\CheckboxField;
use SilverStripe\Forms\DropdownField;
use SilverStripe\Forms\NumericField;
use SilverStripe\Forms\TreeDropdownField;
use SilverStripe\Forms\TextField;
use SilverStripe\ORM\DataExtension;
use SilverStripe\Forms\FieldList;
use SilverStripe\Control\Director;
use SilverStripe\SiteConfig\SiteConfig;

class ExactOnlineSiteConfig extends DataExtension {

    private static $db = array(
        'ExactClientId' => 'Varchar(100)',
        'ExactClientSecret' => 'Varchar(100)',
        'ExactOauth' => 'Text'
    );

    public function updateCMSFields(FieldList $fields)
    {

        $ExactClientIdField = TextField::create('ExactClientId', 'ExactClientId');
        $ExactClientSecretField = TextField::create('ExactClientSecret', 'ExactClientSecret');

        $fields->addFieldsToTab("Root.ExactOnline", array(
            $ExactClientIdField,
            $ExactClientSecretField
        ));

    }

    public function onAfterWrite()
    {

        /*$config = SiteConfig::current_site_config();
        //$config->ExactOauth = $_GET['code'];
        $config->ExactOauth = "morrie";
        $config->write();*/


        /*$connection = new \Picqer\Financials\Exact\Connection();
        $connection->setRedirectUrl(Director::absoluteBaseURL()."ExactController/Authorize"); // Same as entered online in the App Center
        $connection->setExactClientId($this->owner->ExactClientId);
        $connection->setExactClientSecret($this->owner->ExactClientSecret);
        $connection->redirectForAuthorization();*/

        $connection = new \Picqer\Financials\Exact\Connection();
        $connection->setRedirectUrl('http://www.ss-boilerplate.hst1.nl/ExactController/Authorize'); // Same as entered online in the App Center
        $connection->setExactClientId('a9804607-e1b6-4a7b-9ec8-8c670e822510');
        $connection->setExactClientSecret('DSG5SPofzWny');
        $connection->redirectForAuthorization();


        parent::onAfterWrite(); // TODO: Change the autogenerated stub

    }

}